parameters:
   - name: mathworks.licensing.endpoint
     type: string
     default: ""
pool:
   vmImage: 'ubuntu-latest'
steps:
   - task: InstallMATLAB@1
   - task: RunMATLABTests@1
     inputs: 
       sourceFolder: tests
       testResultsJUnit: test-results/results.xml    
