name: Run MATLAB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      inputs:
        endpoint:
          default:
jobs:
  test:
    runs-on: ubuntu-latest
    env: 
      MATHWORKS_LICENSING_ENDPOINT: ${{ github.event.inputs.endpoint }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      # - name: Display endpoint for debugging
      #   uses: echo $MATHWORKS_LICENSING_ENDPOINT
      
      # - name: Set up MATLAB
      #   uses: matlab-actions/setup-matlab@v2

      # - name: Run commands
      #   uses: matlab-actions/run-command@v2
      #   with:
      #     command: pwd

          