name: Run MATLAB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
      inputs:
        endpoint:
          default:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['v1', 'v2']
    env: 
      MATHWORKS_LICENSING_ENDPOINT: ${{ github.event.inputs.endpoint }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Display endpoint for debugging
        run: echo $MATHWORKS_LICENSING_ENDPOINT
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@${{ matrix.version }}

      - name: Run commands
        uses: matlab-actions/run-command@${{ matrix.version }}
        with:
          command: pwd

          